// Frontend/gameficacaoFrontEnd/components/Header.vue
<script>
import { defineComponent } from '@vue/composition-api'

export default defineComponent({
    setup() {
        
    },
    data() {
        return {
            searchText: '' //Armazena oque o usuario digitar
        }
    },
    methods: {
        doSearch() {
            if (this.searchText.trim() === '') {
                alert('Digite algo para buscar')
                return
            }
            console.log('Buscando:', this.searchText)
            //Aqui farei a busca real quando o back estiver pronto
        }
    }
})

</script>

<template>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="left-elements d-flex">
                    <img src="../image/logo2.png" alt="">
                    <i class="bi bi-list"></i>
                </div>
                <div class="right-elements d-flex align-items-center">
                    <div class="search-box d-flex">
                        <input type="text"
                            placeholder="Digite para buscar..."
                            v-model="searchText"
                        >
                        <button @click="doSearch">Buscar</button>
                    </div>
                    <div class="rotas d-flex gap-3">
                        <i class="bi bi-journal-check"></i>
                        <i class="bi bi-mortarboard"></i>
                        <i class="bi bi-bar-chart"></i>
                        <i class="bi bi-book"></i>
                    </div>
                    <i class="bi bi-person-circle"></i>
                </div>
            </div>
        </div>
        <div class="sidebar-esquerdo col-4" style="background-color: rgb(12, 39, 189);">
            <div class="person gap-3">
                <i class="bi bi-person-circle"></i>
                <div class="name">
                    <span class="">IZAIAS RAMOS FRANÇA DE</span>
                </div>
            </div>
            <div class="search-box d-flex p-3">
                    <input type="text"
                        placeholder="Digite para buscar..."
                        v-model="searchText"
                    >
                    <button @click="doSearch">Buscar</button>
            </div>
            <!-- Example single danger button -->
<div class="btn-group">
  <button type="button" class="btn btn-outline-white dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Action
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
</div>
        </div>
    </div>
</template>

<style>
body{
    margin: 0;
    padding: 0;
        flex-shrink: 0;
    box-sizing: border-box;
}
.container-fluid {
    padding: 0;
    margin: 0;
}

.row .col-12{
    background-color: rgb(12, 39, 189);
    height: 9vh;
    display: flex;
    align-items: center; /* alinha verticalmente */
    flex-wrap: nowrap;
        flex-shrink: 0;
}

.row img {
    height: 70px;
    width: auto; /* mantém a proporção */
}

.bi-list {
    font-size: 40px; /* tamanho do ícone */
    color: white; /* cor do ícone */
    padding: 0 20px;
}

.right-elements {
    margin-left:5%;  
    display: flex;
    flex: 1;
    justify-content: space-around;
}
.right-elements i{
    font-size: 30px;
    color: #fff;
}

input {
    padding: 10px;
    width: 400px;
    border: 1px solid #ccc;
    border-radius: 4px 0 0 4px;
}

button {
    padding: 10px 15px;
    background: #2c3e50;
    color: white;
    border: none;
    border-radius: 0 4px 4px 0;
}

button:hover {
    background: #42b983;
}

/* Sidebar Esquerdo */

.sidebar-esquerdo{
    padding: 0;
    margin: 0;
    height: 98.5vw;
}
.person{
    width: 90%;
    display: flex;
    justify-content: center;
    align-items: center;
}
.person i {
    font-size: 40px;
    color: #fff;
    margin-left: 10px;
}
.name {
    color: #fff;
}
@media (max-width: 1000px) {
    input {
        width: 80%;
    }
}
</style>

// Frontend/gameficacaoFrontEnd/src/app/components/header/header.component.ts
import { Component, input } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  // Equivalente ao 'data()' do Vue
  searchText: string = '';

  // Equivalente ao 'methods()' do Vue
  doSearch(): void { // 'void' indica que a função não retorna nada
    if (this.searchText.trim() === '') {
      alert('Digite algo para buscar');
      return;
    }
    console.log('Buscando:', this.searchText);
    // Aqui fará a busca real quando o back estiver pronto
  }
}

<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="left-elements d-flex">
        <img src="assets/image/logo2.png" alt="Logo">
        <i class="bi bi-list"></i>
      </div>
      <div class="right-elements d-flex align-items-center">
        <div class="search-box d-flex">
          <input type="text"
            placeholder="Digite para buscar..."
            [(ngModel)]="searchText"
          >
          <button (click)="doSearch()">Buscar</button>
        </div>
        <div class="rotas d-flex gap-3">
          <i class="bi bi-journal-check"></i>
          <i class="bi bi-mortarboard"></i>
          <i class="bi bi-bar-chart"></i>
          <i class="bi bi-book"></i>
        </div>
        <i class="bi bi-person-circle"></i>
      </div>
    </div>
  </div>
  <div class="sidebar-esquerdo" style="background-color: rgb(12, 39, 189);">
    <div class="person gap-3">
      <i class="bi bi-person-circle"></i>
      <div class="name">
        <span class="">IZAIAS RAMOS FRANÇA DE</span>
      </div>
    </div>
    <div class="search-box">
      <input class="input-sidebar" type="text"
        placeholder="Digite para buscar..."
        [(ngModel)]="searchText"
      >
      <button (click)="doSearch()">Buscar</button>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-outline-white dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Páginas
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" routerLink="/">Home</a>
        <a class="dropdown-item" routerLink="/provas">Provas</a>
        <a class="dropdown-item" routerLink="/provas-feitas">Provas Feitas</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" routerLink="/insights">Insights</a>
      </div>

      <button type="button" class="btn btn-outline-white dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Menu
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" routerLink="/">Home</a>
        <a class="dropdown-item" routerLink="/provas">Provas</a>
        <a class="dropdown-item" routerLink="/provas-feitas">Provas Feitas</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" routerLink="/insights">Insights</a>
      </div>
    </div>
  </div>
</div>
